### ISSUE TITLE
How to establish automated Behat running in a Pipeline?

### ISSUE THREAD

**Issue by ArtuGit** [docksal/bitbucket-pipelines-agent#5]
Can it be a reasonable idea to run Behat tests for a specific pipeline?
Can Behat be performed inside Docksal?
How?

**Comment by lmakarov** [comment]
We have official docs on Behat: http://docs.docksal.io/en/master/tools/behat/
There is also a sample Behat setup in the https://github.com/docksal/drupal7-advanced repo

In terms of running Behat with Docksal - it's absolutely possible.
I'd recommend starting locally with the example in docksal/drupal7-advanced, then read the docs and expand the setup as necessary.

In terms of running Behat with just Bitbucket Pipelines - that won't work.
Bitbucket Pipelines do not support docker-compose and thus provisioning a complete Docksal stack is not possible within just the pipelines runtime environment. You need a standalone server with Docksal installed where the test environments will be provisioned.

**Comment by ArtuGit** [comment]
> I'd recommend starting locally with the example in docksal/drupal7-advanced
I passed it and it works locally.

> You need a standalone server with Docksal installed where the test environments will be provisioned.
This is what I would like to know.
What software should I use on a standalone server with Docksal? 
Is it the same as I use locally? Should I install `fin` on a server?

**Comment by lmakarov** [comment]
Yes, get a server with Ubuntu and follow the standard Docksal setup instructions.

You will also want to open up `docksal-vhost-proxy` to the world (as discussed [here](https://github.com/docksal/docksal/issues/310#issuecomment-321310463)) to be able to access the environments.

**Comment by ArtuGit** [comment]
Thank you
