### ISSUE TITLE
How to add rsync to this image correctly?

### ISSUE THREAD

**Issue by ArtuGit** [docksal/bitbucket-pipelines-agent#8]
Currently I try `docksal/bitbucket-pipelines-agent:php`.

**Comment by lmakarov** [comment]
I'm assuming you want to contribute and this is a very easy contribution in fact :)

The php flavor is built from the base image. Any standard additional packages (available from Alpine repos) would go here: https://github.com/docksal/bitbucket-pipelines-agent/blob/develop/base/Dockerfile#L4-L9

Once the base image is built, the php one can be built from it.

Feel free to submit a PR.
