### ISSUE TITLE
Add gitlab support 

### ISSUE THREAD

**Issue by aczietlow** [docksal/bitbucket-pipelines-agent#9]
The pipeline agent currently supports Bitbucket and Circle CI. Let's add Gitlab to the list

**Comment by lmakarov** [comment]
Yep, great suggestion. Unfortunately, I don not have a project using Gitlab CI at the moment.

Feel free to contribute a PR :)

**Comment by aczietlow** [comment]
My bad, that was the intention. I Forgot to add the keyword to my PR.
